// frontend/src/components/Register.tsx
import React from "react";
import TextInput from "./TextInput";
import { REGISTER_USER } from "../graphql/mutations/register";
import { useMutation } from "@apollo/client";
import { GraphQLErrorExtensions } from "graphql";
import { useUserStore } from "../store/userStore";
import useGeneralStore from "../store/generalStore";

function Register() {
  const [registerUser, { error, data }] = useMutation(REGISTER_USER);
  const setUser = useUserStore((state) => state.setUser);
  const setIsLoginOpen = useGeneralStore((state) => state.setLoginIsOpen);

  //errors is an object with property of email, password, fullname, confirmPassword mapped to an error message. type it properly
  const [errors, setErrors] = React.useState<GraphQLErrorExtensions>({});
  const handleRegister = async () => {
    try {
      setErrors({});
      await registerUser({
        variables: {
          email: loginData.email,
          password: loginData.password,
          fullname: loginData.fullName,
          confirmPassword: loginData.confirmPassword,
        },
      });
      console.log("DATA", data);
      console.log(error?.graphQLErrors[0].extensions);
      setUser(data.register.user);
      setIsLoginOpen(false);
    } catch (_) {
      if (error?.graphQLErrors && error.graphQLErrors[0].extensions) {
        const validationErrors = error.graphQLErrors[0].extensions;
        setErrors(validationErrors);
      }
    }
  };
  const [loginData, setLoginData] = React.useState({
    email: "",
    password: "",
    fullName: "",
    confirmPassword: "",
  });
  return (
    <>
      <div className="text-center text-[28px] mb-4 font-bold">Sign up</div>

      <div className="px-6 pb-2">
        <TextInput
          max={64}
          placeHolder="Enter your full name"
          onChange={(e) =>
            setLoginData({ ...loginData, fullName: e.target.value })
          }
          inputType="email"
          autoFocus={true}
          error={errors?.fullname as string}
        />
      </div>
      <div className="px-6 pb-2">
        <TextInput
          autoFocus={false}
          max={64}
          onChange={(e) =>
            setLoginData({ ...loginData, email: e.target.value })
          }
          placeHolder="Email"
          inputType="text"
          error={errors?.email as string}
        />
      </div>
      <div className="px-6 pb-2">
        <TextInput
          autoFocus={false}
          max={64}
          onChange={(e) =>
            setLoginData({ ...loginData, password: e.target.value })
          }
          placeHolder="Password"
          inputType="password"
          error={errors?.password as string}
        />
      </div>
      <div className="px-6 pb-2">
        <TextInput
          autoFocus={false}
          max={64}
          onChange={(e) =>
            setLoginData({ ...loginData, confirmPassword: e.target.value })
          }
          placeHolder="Confirm Password"
          inputType="password"
          error={errors?.confirmPassword as string}
        />
      </div>
      <div className="px-6 text-[12px] text-gray-600">Forgot password?</div>
      <div className="px-6 mt-6">
        <button
          onClick={handleRegister}
          disabled={
            !loginData.email ||
            !loginData.password ||
            !loginData.fullName ||
            !loginData.confirmPassword
          }
          className={[
            "w-full text-[17px] font-semibold text-white py-3 rounded-sm",
            !loginData.email ||
            !loginData.password ||
            !loginData.fullName ||
            !loginData.confirmPassword
              ? "bg-gray-200"
              : "bg-[#F02C56]",
          ].join(" ")}
        >
          Register
        </button>
      </div>
    </>
  );
}

export default Register;

// nuxt-laravel/frontend/pages/register.vue
<template>
  <AuthLayout>
    <div class="mt-10">
      <h1 class="lg:text-5xl text-3xl text-center font-extrabold">
        Create your account
      </h1>

      <form class="mt-12" @submit.prevent="register()">
        <div>
          <TextInput
            placeholder="Username"
            v-model="name"
            inputType="text"
            :error="errors && errors.name ? errors.name[0] : ''"
          />
        </div>

        <div class="mt-4">
          <TextInput
            placeholder="Email: link@gmail.com"
            v-model="email"
            inputType="email"
            :error="errors && errors.email ? errors.email[0] : ''"
          />
        </div>

        <div class="mt-4">
          <TextInput
            placeholder="Password"
            v-model="password"
            inputType="password"
            :error="errors && errors.password ? errors.password[0] : ''"
          />
        </div>

        <div class="mt-4">
          <TextInput
            placeholder="Confirm Password"
            v-model="confirmPassword"
            inputType="password"
          />
        </div>

        <div class="mt-10">
          <button
            type="submit"
            class="rounded-full w-full p-3 font-bold"
            :disabled="!name || !email || !password || !confirmPassword"
            :class="
              name && email && password && confirmPassword
                ? 'bg-[#8228D9] hover:bg-[#6c21b3] text-white'
                : 'bg-[#EFF0EB] text-[#A7AAA2]'
            "
          >
            Create account
          </button>
        </div>
      </form>

      <div class="text-[14px] text-center pt-12">
        Already have an account?
        <NuxtLink to="/" class="text-[#8228D9] underline"> Log in </NuxtLink>
      </div>
    </div>
  </AuthLayout>
</template>

<script setup>
import AuthLayout from "~/layouts/AuthLayout.vue";
import { useUserStore } from "~~/stores/user";

const userStore = useUserStore();
const router = useRouter();

definePageMeta({ middleware: "is-logged-in" });

let name = ref(null);
let email = ref(null);
let password = ref(null);
let confirmPassword = ref(null);
let errors = ref(null);

const register = async () => {
  errors.value = null;

  try {
    await userStore.getTokens();
    await userStore.register(
      name.value,
      email.value,
      password.value,
      confirmPassword.value
    );

    await userStore.getUser();

    router.push("/admin");
  } catch (error) {
    console.log(error);
    errors.value = error.response.data.errors;
  }
};
</script>
